# Generated by Django 4.2.23 on 2025-08-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_personshirt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Runner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "medal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GOLD", "Gold Medal"),
                            ("SILVER", "Silver Medal"),
                            ("BRONZE", "Bronze Medal"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
