# Generated by Django 4.2.23 on 2025-08-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_runner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fruit",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
